<?php

namespace iMSCP\Proxies\__CG__\iMSCP\ApsStandard\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ApsInstanceSetting extends \iMSCP\ApsStandard\Entity\ApsInstanceSetting implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'id', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'instance', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'group', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'label', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'description', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'name', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'value', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'metadata');
        }

        return array('__isInitialized__', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'id', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'instance', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'group', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'label', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'description', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'name', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'value', '' . "\0" . 'iMSCP\\ApsStandard\\Entity\\ApsInstanceSetting' . "\0" . 'metadata');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ApsInstanceSetting $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getInstance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstance', array());

        return parent::getInstance();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstance(\iMSCP\ApsStandard\Entity\ApsInstance $instance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstance', array($instance));

        return parent::setInstance($instance);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroup', array());

        return parent::getGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroup($group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroup', array($group));

        return parent::setGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', array());

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', array($label));

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', array());

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValue', array($value));

        return parent::setValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetadata()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetadata', array());

        return parent::getMetadata();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetadata(array $metadata)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetadata', array($metadata));

        return parent::setMetadata($metadata);
    }

    /**
     * {@inheritDoc}
     */
    public function validateSettingValue(\Symfony\Component\Validator\Context\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validateSettingValue', array($context));

        return parent::validateSettingValue($context);
    }

}
