<?php

namespace iMSCP\Proxies\__CG__\iMSCP\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Admin extends \iMSCP\Entity\Admin implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminId', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminName', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminPass', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminType', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminSysName', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminSysUid', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminSysGname', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminSysGid', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'domainCreated', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'customerId', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'createdBy', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'fname', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'lname', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'gender', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'firm', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'zip', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'city', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'state', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'country', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'email', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'phone', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'fax', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'street1', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'street2', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'uniqkey', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'uniqkeyTime', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminStatus');
        }

        return array('__isInitialized__', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminId', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminName', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminPass', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminType', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminSysName', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminSysUid', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminSysGname', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminSysGid', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'domainCreated', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'customerId', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'createdBy', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'fname', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'lname', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'gender', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'firm', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'zip', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'city', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'state', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'country', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'email', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'phone', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'fax', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'street1', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'street2', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'uniqkey', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'uniqkeyTime', '' . "\0" . 'iMSCP\\Entity\\Admin' . "\0" . 'adminStatus');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Admin $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAdminId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getAdminId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminId', array());

        return parent::getAdminId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminName($adminName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminName', array($adminName));

        return parent::setAdminName($adminName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminName', array());

        return parent::getAdminName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminPass($adminPass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminPass', array($adminPass));

        return parent::setAdminPass($adminPass);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminPass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminPass', array());

        return parent::getAdminPass();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminType($adminType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminType', array($adminType));

        return parent::setAdminType($adminType);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminType', array());

        return parent::getAdminType();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminSysName($adminSysName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminSysName', array($adminSysName));

        return parent::setAdminSysName($adminSysName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminSysName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminSysName', array());

        return parent::getAdminSysName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminSysUid($adminSysUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminSysUid', array($adminSysUid));

        return parent::setAdminSysUid($adminSysUid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminSysUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminSysUid', array());

        return parent::getAdminSysUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminSysGname($adminSysGname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminSysGname', array($adminSysGname));

        return parent::setAdminSysGname($adminSysGname);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminSysGname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminSysGname', array());

        return parent::getAdminSysGname();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminSysGid($adminSysGid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminSysGid', array($adminSysGid));

        return parent::setAdminSysGid($adminSysGid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminSysGid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminSysGid', array());

        return parent::getAdminSysGid();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomainCreated($domainCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomainCreated', array($domainCreated));

        return parent::setDomainCreated($domainCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomainCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomainCreated', array());

        return parent::getDomainCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerId($customerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerId', array($customerId));

        return parent::setCustomerId($customerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerId', array());

        return parent::getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setFname($fname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFname', array($fname));

        return parent::setFname($fname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFname', array());

        return parent::getFname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLname($lname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLname', array($lname));

        return parent::setLname($lname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLname', array());

        return parent::getLname();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirm($firm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirm', array($firm));

        return parent::setFirm($firm);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirm', array());

        return parent::getFirm();
    }

    /**
     * {@inheritDoc}
     */
    public function setZip($zip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZip', array($zip));

        return parent::setZip($zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZip', array());

        return parent::getZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet1($street1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet1', array($street1));

        return parent::setStreet1($street1);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet1', array());

        return parent::getStreet1();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet2($street2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet2', array($street2));

        return parent::setStreet2($street2);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet2', array());

        return parent::getStreet2();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniqkey($uniqkey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniqkey', array($uniqkey));

        return parent::setUniqkey($uniqkey);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqkey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqkey', array());

        return parent::getUniqkey();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniqkeyTime($uniqkeyTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniqkeyTime', array($uniqkeyTime));

        return parent::setUniqkeyTime($uniqkeyTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqkeyTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqkeyTime', array());

        return parent::getUniqkeyTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminStatus($adminStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminStatus', array($adminStatus));

        return parent::setAdminStatus($adminStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminStatus', array());

        return parent::getAdminStatus();
    }

}
